s=str(input('Introdu sirul dorit:'))
a=s.count(('A'))
print('Numarul de aparitii a caracetrului A',a)
print('Sirul obtinut prin substiruirea caracterului A in *' )
s1=list(s)
s1.remove('B')
s1= ''.join(s1)
print('Sirul obţinut prin radierea din şirul S a tuturor apariţiilor caracterului ’B’:', s1)
print('Numărul de apariţii ale silabei MA în şirul S:', s.count('MA'))
print('Sirul obţinut prin substituirea tuturor apariţiilor în şirul S a silabei MA prin silaba TA:', s.replace('MA','TA'))
print('Scrierea inversă a şirului S:', s[::-1])